volumes:
  postgres-data: { }


services:
  postgres: # Test
    image: "postgres:14.1-alpine"
    hostname: postgresql
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5455:5432"
    env_file:
      - .env

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.10
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
